CREATE TABLE Audits (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(50),
    action VARCHAR2(20),
    changed_at DATE
);

CREATE OR REPLACE TRIGGER trg_audit_accounts
AFTER INSERT OR UPDATE OR DELETE ON Accounts
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    
    INSERT INTO Audits (table_name, action, changed_at)
    VALUES ('Accounts', v_action, SYSDATE);
END;
/
